openapi: 3.1.0
info:
  version: 1.0.0
  title: Lehlehka App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Lehlehka App
tags:
servers:
  - url: http://localhost:3000
paths:
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
