openapi: 3.1.0
info:
  version: 1.0.0
  title: Lehlehka App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Lehlehka App
tags:
  - name: Weeks
    description: Getting baby and mom info by date
  - name: Diaries
    description: Operations related to diary entries, including create, read, update, and delete
  - name: Tasks
    description: Operations related to tasks including create, read, and update
servers:
  - url: http://localhost:3000
  - url: https://project-teamsurvivors.onrender.com
security:
  - bearerAuth: []
paths:
  /api/weeks/my-day/{estimateBirthDate}:
    get:
      $ref: ../swagger/paths/week/my-day/get.yaml
  /api/weeks/my-day-demo:
    get:
      $ref: ../swagger/paths/week/my-day-demo/get.yaml
  /api/weeks/baby-state/{currentWeek}:
    get:
      $ref: ../swagger/paths/week/baby-state/get.yaml
  /api/weeks/mom-state/{currentWeek}:
    get:
      $ref: ../swagger/paths/week/mom-state/get.yaml

  /api/diaries:
    get:
      $ref: ../swagger/paths/diaries/get.yaml
    post:
      $ref: ../swagger/paths/diaries/post.yaml
  /api/diaries/{entryId}:
    get:
      $ref: ../swagger/paths/diaries/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/diaries/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/diaries/{id}/delete.yaml

  /api/tasks:
    get:
      $ref: ../swagger/paths/tasks/get.yaml
    post:
      $ref: ../swagger/paths/tasks/post.yaml
  /api/diaries/{entryId}:
    patch:
      $ref: ../swagger/paths/tasks/{id}/patch.yaml

  /api/auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /api/auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /api/auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
  /api/auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
