openapi: 3.1.0
info:
  version: 1.0.0
  title: Lehlehka App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Lehlehka App
tags:
  - name: Weeks
    description: Getting baby and mom info by date
servers:
  - url: http://localhost:3000
  - url: https://project-teamsurvivors.onrender.com
paths:
  /api/weeks/my-day/{estimateBirthDate}:
    get:
      $ref: ../swagger/paths/week/my-day/get.yaml
  /api/weeks/my-day-demo:
    get:
      $ref: ../swagger/paths/week/my-day-demo/get.yaml
  /api/weeks/baby-state/{currentWeek}:
    get:
      $ref: ../swagger/paths/week/baby-state/get.yaml
  /api/weeks/mom-state/{currentWeek}:
    get:
      $ref: ../swagger/paths/week/mom-state/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
