tags:
  - Tasks
summary: Get all tasks of the authenticated user
operationId: getTasks
description: Returns a list of all tasks for the authenticated user.
security:
  - bearerAuth: []
responses:
  '200':
    description: Successfully fetched tasks
    content:
      application/json:
        schema:
          type: object
          required:
            - status
            - message
            - data
          properties:
            status:
              type: integer
              example: 200
            message:
              type: string
              example: Successfully fetched tasks!
            data:
              type: array
              items:
                $ref: '../../components/schemas/task.yaml'
  '401':
    $ref: '../../components/responses/401.yaml'
